[project]
name = "qualbum"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.8.*"
dependencies = [
    "beautifulsoup4==4.9.0",
    "lxml==4.5.0",
    "mistune==0.8.4",
    "pillow==8.4.*",
    "pyyaml==5.3.1",
]
